version: 0.2
phases:
  install:
      runtime-versions: 
      Node.js: 12.6
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda2507 --output-template-file outputsamTemplate.yaml 
 artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamTemplate.yaml