version: 0.2
phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  install:
    commands:
      - aws cloudformation package --template-file https://github.com/Ramki0487/Ramki.git/SamTemplate.yml --s3-bucket lambda2507 --output-template-file outputSamTemplate.yml 
