AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS:Serverless-2016-10-31
service: AWS::Serverless::Function
provider:
  name: aws
  stage: dev
  region: ap-south-1
  memorySize: 512
  Timeout: 30
  CodeUri: ./
  Runtime: nodejs10.x
  Policies:
        # Give Lambda basic execution Permission to the scheduledEventLogger
        - AWSLambdaBasicExecutionRole

functions:
  nextJsApp:
    handler: serverless/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: GET

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true